services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MARIADB_PORT}:3306"
    command:
      --lower_case_table_names=1
    restart: unless-stopped
    volumes:
      - ./db/db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
    - boardNet

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile  # backend 디렉토리 안의 dockerfile 참조
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
    ports:
      - "8080:8080"  # 애플리케이션이 8080 포트에서 실행됨
    depends_on:
      - mariadb
    networks:
      - boardNet
    restart: unless-stopped

networks:
  boardNet:
    driver: bridge
    name: boardNet